### ISSUE TITLE
Code from Chase bank not found

### ISSUE THREAD

**Issue by 615don** [squatto/alfred-imessage-2fa#13]
The following is the text of the message (where XXXXXXXX is 8 digits, no space and no space to the leading colon): 

`From: Chase Online
Reminder: We'll never call you to ask for this code
Enter online at prompt, expires in 30 min.
One-Time Code:XXXXXXXX`

**Comment by 615don** [comment]
Not sure whether I should create an additional issue but I just noticed AirBNB was also not detected: Sample below (where XXXX is 4 digits, no spaces, does have leading space to the colon, no trailing space to the period):

`Your Airbnb verification code is: XXXX. Don't share this code with anyone; our employees will never ask for the code`

**Comment by squatto** [comment]
Thank you for letting me know about this! I'll add some patterns and push a new release. Stripe recently started pushing `XXX-XXX` auth codes, so I'll add that too.

**Comment by squatto** [comment]
I think that you may be running an old version of the workflow, actually. 8 digit Chase codes are detected with the current version, including when they have a leading colon or trailing period.

I'm adding support for 4 digit codes, but I'm making it very specific. The 4 digit code has to be preceded by `code:` or `is:` and an optional whitespace. This prevents things like a year from being detected as a 2FA code. With how much we're all complaining about 2020, it'll happen a lot 😂

**Comment by squatto** [comment]
@615don 4 digit code support has been added to [the latest release - v1.2.3](https://github.com/squatto/alfred-imessage-2fa/releases/tag/v1.2.3).

Direct download link to the workflow file: https://github.com/squatto/alfred-imessage-2fa/releases/download/v1.2.3/iMessage.2FA.alfredworkflow

Thanks again for the suggestion!

**Comment by 615don** [comment]
Interesting. I was on 1.2.2. Using the 1.2.3 you linked made things work for me though so I'm happy. Thanks!

**Comment by squatto** [comment]
I'm glad to hear it! You're welcome!
