### ISSUE TITLE
the code with other language seems difficult to figure out

### ISSUE THREAD

**Issue by caidwang** [squatto/alfred-imessage-2fa#15]
os version: MacOS 10.15.7
Alfred version: 4.1
workflow version: 1.2.3

It seems difficult to figure out code with other language. For instance, the message content like this can't be detected, "您的验证码是 199035，10分钟内有效，请勿泄露" and "登录验证码：627823，您正在尝试【登录】，10分钟内有效" as well. However, the content like this can be detected correctly, "【赛验】验证码 54538".

I'm not sure it the language that makes detection difficult, or the location of the code in content make it wrong.

**Comment by squatto** [comment]
Thank you for letting me know about this. I will do some testing on my end and see if I can figure out what is going on. I'll update you soon.

**Comment by squatto** [comment]
This has been fixed in the latest release. You can download it here: https://github.com/squatto/alfred-imessage-2fa/releases/download/v1.2.4/iMessage.2FA.alfredworkflow

Thanks again for letting me know about this!

**Comment by caidwang** [comment]
> This has been fixed in the latest release. You can download it here: https://github.com/squatto/alfred-imessage-2fa/releases/download/v1.2.4/iMessage.2FA.alfredworkflow
> 
> Thanks again for letting me know about this!

Thank you for your contributions!
