### ISSUE TITLE
Feature Request: Mark As Read

### ISSUE THREAD

**Issue by georgeh** [squatto/alfred-imessage-2fa#17]
Would it be possible to mark the message as read when it gets copied? I get alerts on my phone and have badges in Messages if I don't manually view the message.

**Comment by squatto** [comment]
I probably _could_ do that, but honestly, I'd be too concerned about the possibility (however likely or unlikely it may be) of causing issues with someone's Messages database file. Heaven forbid the file becomes corrupted and someone loses their entire message history 😬

It's a great suggestion - and one that I would appreciate having myself - but I just can't get past my concerns enough to implement it. Thank you for the suggestion though!

**Comment by georgeh** [comment]
Yeah, I get your hesitance to start updating an undocumented database as important as the messages DB. Hopefully Apple will provide an API at some point. Thanks for looking and working on this, it's my favorite workflow!

**Comment by squatto** [comment]
It would be wonderful if they would, that's for sure.

Thank you very much for the kind words! I'm thrilled that you love the workflow!
