### ISSUE TITLE
ERROR: Unable to Access Your Messages in M1

### ISSUE THREAD

**Issue by Ryan-Efendy** [squatto/alfred-imessage-2fa#20]
In my Intel Macbook I was able to set it up and access my 2fa in my iMessage but I'm getting into this error in my M1 Macbook:

<img width="191" alt="Screen Shot 2021-05-23 at 9 22 16 AM" src="https://user-images.githubusercontent.com/12979345/119268564-6054c480-bba8-11eb-872b-39be89d23bf3.png">

<img width="417" alt="Screen Shot 2021-05-23 at 9 21 52 AM" src="https://user-images.githubusercontent.com/12979345/119268550-5337d580-bba8-11eb-8949-ece887f28a32.png">

**Comment by squatto** [comment]
Thank you for letting me know you’re having an issue. Have you granted full disk access to Alfred? That has typically been what fixes this issue in the past. You can find the official instructions [on this page](https://www.alfredapp.com/help/getting-started/permissions/). Let me know if that fixes it (or not!)

**Comment by Ryan-Efendy** [comment]
Yes after granting Alfred full disk access it works 🎉

**Comment by squatto** [comment]
Excellent! I'm glad that fixed it for you @Ryan-Efendy

**Comment by codebykat** [comment]
@squatto Just a quick comment that I hit this problem as well after migrating my existing data to an M1 mac. It took some digging to find this issue (full disk access was the solution) -- I wonder if the error message can be updated, or perhaps a line added to [this page](https://pacmax.org/git_repo/squatto-alfred-imessage-2fa/)? (I'm assuming there's no way to have a workflow trigger the prompt for full disk access.)

Thanks for your work on this utility, I've been using it for ages and it's a real time-saver.
