### ISSUE TITLE
Not working on Big sur

### ISSUE THREAD

**Issue by chrisgrieser** [squatto/alfred-imessage-2fa#22]
I used this excellent workflow for a bit but recently updated to Big Sur.
Since then, it stopped working. Maybe the location of the imessage database moved or something? :/

And yes, I have checked, Alfred still has automation access to System events.

```OS: macOS 11.4 20F71 x86_64
Host: iMac19,2
Kernel: 20.5.0
Uptime: 3 hours, 25 mins
Packages: 127 (brew)
Shell: zsh 5.8
Resolution: 1680x945@2x, 900x1600@2x
DE: Aqua
WM: Quartz Compositor
WM Theme: Blue (Light)
Terminal: iTerm2
Terminal Font: Menlo-Regular 24
CPU: Intel i3-8100 (4) @ 3.60GHz
GPU: Radeon Pro 555X
Memory: 9379MiB / 16384MiB
```

<img width="990" alt="Screen Shot 2021-06-07 at 16 13 13" src="https://user-images.githubusercontent.com/73286100/121032628-bbdba080-c7ab-11eb-8557-2046c5ae1cab.png">

**Comment by chrisgrieser** [comment]
okay, I do not know what changed, but suddenly, it is working. strange.

**Comment by squatto** [comment]
That's very strange! If it stops again please let me know and I'll be happy to help you figure it out. I'm on Big Sur and it works great, so there was definitely something else at play.
