### ISSUE TITLE
Stopped working for me after Monterey update

### ISSUE THREAD

**Issue by AnKingMed** [squatto/alfred-imessage-2fa#25]
It still pulls up in alfred, but it can no longer find the codes in imessage

**Comment by hoium** [comment]
For users with multiple Macs - Intel & `M*` and PHP installed via brew I added the following to help with sync

```
export PATH=$PATH:/usr/local/bin/:/opt/homebrew/bin/
php find-messages.php $look_back_minutes
```

**Comment by squatto** [comment]
Thanks for working through this! I just released a new version that figures out where `php` is located on your system. It checks for these paths and uses the first one it finds:

* `php`
* `/usr/local/bin/php`
* `/opt/local/bin/php`
* `/opt/homebrew/bin/php`
* `/usr/bin/php`

[You can download the latest release here](https://github.com/squatto/alfred-imessage-2fa/releases/latest/download/iMessage.2FA.alfredworkflow)
