### ISSUE TITLE
Add support for Chase codes

### ISSUE THREAD

**Issue by chrismessina** [squatto/alfred-imessage-2fa#26]
Here's an example text message:

```
From: Chase
We'll NEVER call you to ask for this code.
One-Time Code:40502888
Only use this online. Code expires in 30 min.
```

**Comment by squatto** [comment]
This is working for me. Are you getting the message that says that no codes were found?

![image](https://user-images.githubusercontent.com/748444/140565791-04e940e8-f6ff-4dda-89f2-1704fc0894ab.png)
